### ISSUE TITLE
ValueError: inputs must not be empty

### ISSUE THREAD

**Issue by saurabhhssaurabh** [juung/Relation-Network#5]
I executed following command:

$ python preprocessing.py --path tasks_1-20_v1-2/en/
It prints "Masking success!" three times. Then I executed:

$python train.py
It gave me ValueError:

Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main()
  File "train.py", line 109, in main
    rn = Model(config)
  File "/home/teamai/saurabh_do_not_delete/relational_network/Relation-Network/model.py", line 74, in __init__
    self.pred = self.build(is_train=is_train)
  File "/home/teamai/saurabh_do_not_delete/relational_network/Relation-Network/model.py", line 228, in build
    embedded_c = self.contextLSTM(self.context, self.label, self.context_real_len, reuse = None)
  File "/home/teamai/saurabh_do_not_delete/relational_network/Relation-Network/model.py", line 134, in contextLSTM
    s_embedded = sentenceLSTM(sentences, real_lens, reuse = reuse)
  File "/home/teamai/saurabh_do_not_delete/relational_network/Relation-Network/model.py", line 112, in sentenceLSTM
    outputs, _ = rnn.static_rnn(lstm_cell, s_input, dtype = tf.float32, scope = scope)
  File "/home/teamai/py2env/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 1162, in static_rnn
    raise ValueError("inputs must not be empty")

Can somebody help me to figure out why inputs are comming empty ?

**Comment by saurabhhssaurabh** [comment]
I found the problem, I provided incorrect path value. It should be:

$python preprocessing.py --path ./

**Comment by vyomraj** [comment]
Hi instead of pointing to files inside the tasks_1-20_v1-2 folder point to the folder where the folder "tasks_1-20_v1-2" is.
Example in my case:
python preprocessing.py --path /Users/vyomraj/Desktop/Research/
Inside the Research folder I had tasks_1-20_v1-2
